export const OPTIONS_LIST = [
	{ value: 'Açaí' },
	{ value: 'Apple' },
	{ value: 'Akee' },
	{ value: 'Apricot' },
	{ value: 'Avocado' },
	{ value: 'Banana' },
	{ value: 'Bilberry' },
	{ value: 'Blackberry' },
	{ value: 'Blackcurrant' },
	{ value: 'Black sapote' },
	{ value: 'Blueberry' },
	{ value: 'Boysenberry' },
	{ value: "Buddha's hand" },
	{ value: 'Crab apples' },
	{ value: 'Currant' },
	{ value: 'Cherry' },
	{ value: 'Cherimoya' },
	{ value: 'Chico fruit' },
	{ value: 'Cloudberry' },
	{ value: 'Coconut' },
	{ value: 'Cranberry' },
	{ value: 'Cucumber' },
	{ value: 'Damson' },
	{ value: 'Date' },
	{ value: 'Dragonfruit' },
	{ value: 'Pitaya' },
	{ value: 'Durian' },
	{ value: 'Elderberry' },
	{ value: 'Feijoa' },
	{ value: 'Fig' },
	{ value: 'Goji berry' },
	{ value: 'Gooseberry' },
	{ value: 'Grape' },
	{ value: 'Raisin' },
	{ value: 'Grapefruit' },
	{ value: 'Guava' },
	{ value: 'Honeyberry' },
	{ value: 'Huckleberry' },
	{ value: 'Jabuticaba' },
	{ value: 'Jackfruit' },
	{ value: 'Jambul' },
	{ value: 'Japanese plum' },
	{ value: 'Jostaberry' },
	{ value: 'Jujube' },
	{ value: 'Juniper berry' },
	{ value: 'Kiwano' },
	{ value: 'Kiwifruit' },
	{ value: 'Kumquat' },
	{ value: 'Lemon' },
	{ value: 'Lime' },
	{ value: 'Loquat' },
	{ value: 'Longan' },
	{ value: 'Lychee' },
	{ value: 'Mango' },
	{ value: 'Mangosteen' },
	{ value: 'Marionberry' },
	{ value: 'Melon' },
	{ value: 'Cantaloupe' },
	{ value: 'Honeydew' },
	{ value: 'Watermelon' },
	{ value: 'Miracle fruit' },
	{ value: 'Mulberry' },
	{ value: 'Nectarine' },
	{ value: 'Nance' },
	{ value: 'Olive' },
	{ value: 'Orange' },
	{ value: 'Blood orange' },
	{ value: 'Clementine' },
	{ value: 'Mandarine' },
	{ value: 'Tangerine' },
	{ value: 'Papaya' },
	{ value: 'Passionfruit' },
	{ value: 'Peach' },
	{ value: 'Pear' },
	{ value: 'Persimmon' },
	{ value: 'Plantain' },
	{ value: 'Plum' },
	{ value: 'Prune' },
	{ value: 'Pineapple' },
	{ value: 'Pineberry' },
	{ value: 'Plumcot' },
	{ value: 'Pomegranate' },
	{ value: 'Pomelo' },
	{ value: 'Purple mangosteen' },
	{ value: 'Quince' },
	{ value: 'Raspberry' },
	{ value: 'Salmonberry' },
	{ value: 'Rambutan' },
	{ value: 'Redcurrant' },
	{ value: 'Salal' },
	{ value: 'Salak' },
	{ value: 'Satsuma' },
	{ value: 'Soursop' },
	{ value: 'Star apple' },
	{ value: 'Star fruit' },
	{ value: 'Strawberry' },
	{ value: 'Surinam cherry' },
	{ value: 'Tamarillo' },
	{ value: 'Tamarind' },
	{ value: 'Ugli fruit' },
	{ value: 'White currant' },
	{ value: 'White sapote' },
	{ value: 'Yuzu' },
	{ value: 'Avocado' },
	{ value: 'Bell pepper' },
	{ value: 'Chili pepper' },
	{ value: 'Corn kernel' },
	{ value: 'Cucumber' },
	{ value: 'Eggplant' },
	{ value: 'Olive' },
	{ value: 'Pea' },
	{ value: 'Pumpkin' },
	{ value: 'Squash' },
	{ value: 'Tomato' },
	{ value: 'Zucchini' }
];